apiVersion: apps/v1
kind: Deployment
metadata:
  name: techportal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techportal
  template:
    metadata:
      labels:
        app: techportal
    spec:
      containers:
      - name: techportal-app
        image: techportal:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081